import { useState, type ReactNode } from 'react'
import { useTranslation } from 'react-i18next'
import { CalendarDays, Image as ImageIcon, Package, Target } from 'lucide-react'
import Modal from '@/components/common/Modal'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import type { NewGoal, PurchasePriority } from '@/services/purchaseGoalsService'

type FormState={name:string;notes:string;currency:string;priority:PurchasePriority;targetDate:string;expectedMonthlySaving:string;itemName:string;currentPrice:string;targetPrice:string;imageUrl:string;productUrl:string;category:string;imageFit:'COVER'|'CONTAIN';imagePositionX:number;imagePositionY:number;imageZoom:number}
const initial:FormState={name:'',notes:'',currency:'TRY',priority:'MEDIUM',targetDate:'',expectedMonthlySaving:'',itemName:'',currentPrice:'',targetPrice:'',imageUrl:'',productUrl:'',category:'',imageFit:'COVER',imagePositionX:50,imagePositionY:50,imageZoom:1}
function Field({label,hint,required,children}:{label:string;hint?:string;required?:boolean;children:ReactNode}){return <label className="block space-y-1.5"><span className="text-sm font-semibold text-slate-800 dark:text-slate-200">{label}{required&&<span className="ml-1 text-red-500">*</span>}</span>{children}{hint&&<span className="block text-xs leading-5 text-slate-500">{hint}</span>}</label>}

export default function GoalForm({open,onClose,onSave}:{open:boolean;onClose:()=>void;onSave:(v:NewGoal)=>Promise<void>}){
 const {t}=useTranslation();const [busy,setBusy]=useState(false);const [v,setV]=useState<FormState>(initial);const input='h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 dark:border-slate-700 dark:bg-slate-950';const priorities=['MUST_HAVE','HIGH','MEDIUM','LOW','SOMEDAY'] as PurchasePriority[]
 function close(){if(!busy){setV(initial);onClose()}}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await onSave({name:v.name,notes:v.notes,currency:v.currency,priority:v.priority,targetDate:v.targetDate?new Date(v.targetDate).toISOString():null,expectedMonthlySaving:Number(v.expectedMonthlySaving||0),items:v.itemName?[{name:v.itemName,currentPrice:Number(v.currentPrice||0),targetPrice:v.targetPrice===''?null:Number(v.targetPrice),currency:v.currency,imageUrl:v.imageUrl,productUrl:v.productUrl,category:v.category,priority:v.priority,status:'WANTED',imageFit:v.imageFit,imagePositionX:v.imagePositionX,imagePositionY:v.imagePositionY,imageZoom:v.imageZoom}]:[]});setV(initial);onClose()}finally{setBusy(false)}}
 return <Modal isOpen={open} onClose={close} title={t('purchaseGoals.form.title')} maxWidth="max-w-5xl"><form onSubmit={submit} className="space-y-6">
  <div className="rounded-2xl border border-indigo-100 bg-indigo-50/60 p-4 dark:border-indigo-900/60 dark:bg-indigo-950/30"><p className="font-semibold text-indigo-950 dark:text-indigo-100">{t('purchaseGoals.form.introTitle')}</p><p className="mt-1 text-sm leading-6 text-indigo-700 dark:text-indigo-300">{t('purchaseGoals.form.intro')}</p></div>
  <section className="space-y-4"><div className="flex items-center gap-3"><span className="rounded-xl bg-indigo-100 p-2 text-indigo-600 dark:bg-indigo-950"><Target size={20}/></span><div><h3 className="font-bold dark:text-white">{t('purchaseGoals.form.goalSection')}</h3><p className="text-sm text-slate-500">{t('purchaseGoals.form.goalSectionHint')}</p></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label={t('purchaseGoals.fields.goalName')} hint={t('purchaseGoals.hints.goalName')} required><input required className={input} placeholder={t('purchaseGoals.placeholders.goalName')} value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></Field><Field label={t('purchaseGoals.fields.priority')} hint={t('purchaseGoals.hints.priority')}><Select value={v.priority} onValueChange={x=>setV({...v,priority:x as PurchasePriority})}><SelectTrigger className="h-11 w-full rounded-xl"><SelectValue/></SelectTrigger><SelectContent searchable={false}>{priorities.map(x=><SelectItem key={x} value={x}>{t(`purchaseGoals.priorities.${x}`)}</SelectItem>)}</SelectContent></Select></Field><Field label={t('purchaseGoals.fields.monthlySaving')} hint={t('purchaseGoals.hints.monthlySaving')}><input min="0" step="0.01" type="number" className={input} placeholder="0" value={v.expectedMonthlySaving} onChange={e=>setV({...v,expectedMonthlySaving:e.target.value})}/></Field><Field label={t('purchaseGoals.fields.targetDate')} hint={t('purchaseGoals.hints.targetDate')}><div className="relative"><CalendarDays className="pointer-events-none absolute left-3 top-3.5 size-4 text-slate-400"/><input type="date" className={`${input} pl-10`} value={v.targetDate} onChange={e=>setV({...v,targetDate:e.target.value})}/></div></Field></div><Field label={t('purchaseGoals.fields.notes')} hint={t('purchaseGoals.hints.notes')}><textarea rows={3} className={`${input} h-auto py-3`} placeholder={t('purchaseGoals.placeholders.notes')} value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></Field></section>
  <div className="h-px bg-slate-200 dark:bg-slate-800"/>
  <section className="space-y-4"><div className="flex items-center gap-3"><span className="rounded-xl bg-emerald-100 p-2 text-emerald-600 dark:bg-emerald-950"><Package size={20}/></span><div><h3 className="font-bold dark:text-white">{t('purchaseGoals.form.productSection')}</h3><p className="text-sm text-slate-500">{t('purchaseGoals.form.productSectionHint')}</p></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label={t('purchaseGoals.fields.productName')} hint={t('purchaseGoals.hints.productName')}><input className={input} placeholder={t('purchaseGoals.placeholders.productName')} value={v.itemName} onChange={e=>setV({...v,itemName:e.target.value})}/></Field><Field label={t('purchaseGoals.fields.category')} hint={t('purchaseGoals.hints.category')}><input className={input} placeholder={t('purchaseGoals.placeholders.category')} value={v.category} onChange={e=>setV({...v,category:e.target.value})}/></Field><Field label={t('purchaseGoals.fields.currentPrice')} hint={t('purchaseGoals.hints.currentPrice')} required><div className="flex gap-2"><input required min="0" step="0.01" type="number" className={input} placeholder="0.00" value={v.currentPrice} onChange={e=>setV({...v,currentPrice:e.target.value})}/><Select value={v.currency} onValueChange={x=>setV({...v,currency:x})}><SelectTrigger className="h-11 w-28 rounded-xl"><SelectValue/></SelectTrigger><SelectContent searchable={false}>{['TRY','USD','EUR'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div></Field><Field label={t('purchaseGoals.fields.targetPrice')} hint={t('purchaseGoals.hints.targetPrice')}><input min="0" step="0.01" type="number" className={input} placeholder={t('purchaseGoals.placeholders.optional')} value={v.targetPrice} onChange={e=>setV({...v,targetPrice:e.target.value})}/></Field><Field label={t('purchaseGoals.fields.productUrl')} hint={t('purchaseGoals.hints.productUrl')}><input type="url" className={input} placeholder="https://…" value={v.productUrl} onChange={e=>setV({...v,productUrl:e.target.value})}/></Field><Field label={t('purchaseGoals.fields.imageUrl')} hint={t('purchaseGoals.hints.imageUrl')}><input type="url" className={input} placeholder="https://…/image.jpg" value={v.imageUrl} onChange={e=>setV({...v,imageUrl:e.target.value})}/></Field></div></section>
  <section className="rounded-2xl border bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950"><div className="mb-4 flex items-center gap-3"><ImageIcon className="text-violet-500"/><div><h3 className="font-bold dark:text-white">{t('purchaseGoals.form.imageSection')}</h3><p className="text-sm text-slate-500">{t('purchaseGoals.form.imageSectionHint')}</p></div></div><div className="grid gap-5 lg:grid-cols-[220px_1fr]"><div className="flex h-40 items-center justify-center overflow-hidden rounded-xl border bg-white dark:border-slate-700 dark:bg-slate-900">{v.imageUrl?<img src={v.imageUrl} alt="" className="h-full w-full" style={{objectFit:v.imageFit==='COVER'?'cover':'contain',objectPosition:`${v.imagePositionX}% ${v.imagePositionY}%`,transform:`scale(${v.imageZoom})`}}/>:<span className="px-4 text-center text-sm text-slate-400">{t('purchaseGoals.form.previewEmpty')}</span>}</div><div className="space-y-4"><Field label={t('purchaseGoals.fields.imageFit')}><Select value={v.imageFit} onValueChange={x=>setV({...v,imageFit:x as 'COVER'|'CONTAIN'})}><SelectTrigger className="h-11 w-full rounded-xl"><SelectValue/></SelectTrigger><SelectContent searchable={false}><SelectItem value="COVER">{t('purchaseGoals.imageFit.COVER')}</SelectItem><SelectItem value="CONTAIN">{t('purchaseGoals.imageFit.CONTAIN')}</SelectItem></SelectContent></Select></Field><div className="grid gap-3 sm:grid-cols-3">{([['imagePositionX',0,100,t('purchaseGoals.fields.horizontal'),'%'],['imagePositionY',0,100,t('purchaseGoals.fields.vertical'),'%'],['imageZoom',1,3,t('purchaseGoals.fields.zoom'),'x']] as const).map(([key,min,max,label,suffix])=><label key={key} className="text-xs font-semibold text-slate-600 dark:text-slate-300">{label}: {v[key]}{suffix}<input className="mt-2 w-full accent-indigo-600" type="range" min={min} max={max} step={key==='imageZoom'?0.1:1} value={v[key]} onChange={e=>setV({...v,[key]:+e.target.value})}/></label>)}</div></div></div></section>
  <div className="flex flex-col-reverse gap-3 border-t pt-5 dark:border-slate-800 sm:flex-row sm:justify-end"><button type="button" onClick={close} className="rounded-xl border px-5 py-2.5 font-semibold dark:border-slate-700">{t('purchaseGoals.actions.cancel')}</button><button disabled={busy} className="rounded-xl bg-indigo-600 px-6 py-2.5 font-semibold text-white disabled:opacity-60">{busy?t('purchaseGoals.actions.saving'):t('purchaseGoals.actions.create')}</button></div>
 </form></Modal>
}
