import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useSearchParams } from 'react-router-dom'
import { Area, AreaChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Search } from 'lucide-react'
import Modal from '@/components/common/Modal'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { tradeExplorerApi, type Filters, type Option, type Statistics, type TradeDetail, type TradePage, type TradeRow } from '@/services/tradeExplorerService'
import { useToast } from '@/contexts/ToastContext'

const emptyStats:Statistics={total:0,winners:0,losers:0,open:0,winRate:0,averageReturn:0,averageWinner:0,averageLoser:0,averageHoldingDays:0,averageFees:0}
function FilterSelect({value,onChange,items,all}:{value:string;onChange:(v:string)=>void;items:Option[];all:string}){return <Select value={value||'ALL'} onValueChange={v=>onChange(v==='ALL'?'':v)}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent searchable={items.length>6}><SelectItem value="ALL">{all}</SelectItem>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
const money=(v:number,locale:string)=>`$${Number(v||0).toLocaleString(locale,{maximumFractionDigits:2})}`
const percent=(v:number)=>`${v>=0?'+':''}${Number(v||0).toFixed(2)}%`

export default function TradeExplorerPage(){
 const {t,i18n}=useTranslation(),toast=useToast(),locale=i18n.language.startsWith('tr')?'tr-TR':'en-US'
 const [searchParams,setSearchParams]=useSearchParams()
 const [filters,setFilters]=useState<Filters>({result:'',page:1,pageSize:25,sort:'entry',direction:'desc'}),[page,setPage]=useState<TradePage>({items:[],total:0,page:1,pageSize:25}),[stats,setStats]=useState(emptyStats),[options,setOptions]=useState<{coins:Option[];strategies:Option[];runs:Option[]}>({coins:[],strategies:[],runs:[]}),[detail,setDetail]=useState<TradeDetail|null>(null),[loading,setLoading]=useState(true),[note,setNote]=useState('')
 const errorMessage=(error:unknown)=>error instanceof Error?error.message:t('common.error')
 const load=async()=>{setLoading(true);try{const [p,s]=await Promise.all([tradeExplorerApi.list(filters),tradeExplorerApi.statistics(filters)]);setPage(p);setStats(s)}catch(error){toast.error(errorMessage(error))}finally{setLoading(false)}}
 useEffect(()=>{void tradeExplorerApi.options().then(setOptions).catch(error=>toast.error(errorMessage(error)))},[]);useEffect(()=>{void load()},[filters])
 const update=(next:Partial<Filters>)=>setFilters(f=>({...f,...next,page:next.page??1}));const open=async(row:TradeRow)=>{try{const value=await tradeExplorerApi.detail(row.id);setDetail(value);setNote(value.trade.note||'')}catch(error){toast.error(errorMessage(error))}}
 const saveNote=async()=>{if(!detail)return;try{await tradeExplorerApi.note(detail.trade.id,note);setDetail({...detail,trade:{...detail.trade,note}});toast.success(t('common.success'))}catch(error){toast.error(errorMessage(error))}}
 useEffect(()=>{const id=Number(searchParams.get('tradeId'));if(!id)return;void tradeExplorerApi.detail(id).then(value=>{setDetail(value);setNote(value.trade.note||'');setSearchParams({}, {replace:true})}).catch(error=>toast.error(errorMessage(error)))},[searchParams,setSearchParams])
 const pages=Math.max(1,Math.ceil(page.total/page.pageSize));const statCards=[[t('tradeExplorer.total'),stats.total],[t('tradeExplorer.winRate'),`${stats.winRate.toFixed(1)}%`],[t('tradeExplorer.avgReturn'),percent(stats.averageReturn)],[t('tradeExplorer.avgWinner'),percent(stats.averageWinner)],[t('tradeExplorer.avgLoser'),percent(stats.averageLoser)]]
 const tabs=[['',t('tradeExplorer.all')],['winner',t('tradeExplorer.winners')],['loser',t('tradeExplorer.losers')],['open',t('tradeExplorer.open')],['closed',t('tradeExplorer.closed')]]
 return <div className="page-shell"><section className="page-hero"><div className="relative z-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-indigo-300">Research workspace</p><h1 className="mt-2 text-3xl font-bold">{t('tradeExplorer.title')}</h1><p className="mt-2 text-slate-300">{t('tradeExplorer.subtitle')}</p></div></section>
 <div className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-800 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-200">{t('tradeExplorer.dailyClose')}</div>
 <section className="surface-card space-y-4 p-4"><div className="flex flex-wrap gap-2">{tabs.map(([v,label])=><button key={v} onClick={()=>update({result:v})} className={`rounded-full px-4 py-2 text-sm font-semibold ${filters.result===v?'bg-indigo-600 text-white':'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300'}`}>{label}</button>)}</div><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-7"><FilterSelect value={filters.coin??''} onChange={v=>update({coin:v})} items={options.coins} all={t('tradeExplorer.coin')}/><FilterSelect value={filters.strategyId??''} onChange={v=>update({strategyId:v})} items={options.strategies} all={t('tradeExplorer.strategy')}/><FilterSelect value={filters.runId??''} onChange={v=>update({runId:v})} items={options.runs} all={t('tradeExplorer.run')}/><FilterSelect value={filters.runType??''} onChange={v=>update({runType:v})} items={[{value:'BACKTEST',label:'BACKTEST'},{value:'FORWARD_TEST',label:'FORWARD_TEST'}]} all={t('tradeExplorer.runType')}/><input type="date" className="rounded-lg border bg-transparent px-3" value={filters.from??''} onChange={e=>update({from:e.target.value})}/><input type="date" className="rounded-lg border bg-transparent px-3" value={filters.to??''} onChange={e=>update({to:e.target.value})}/><FilterSelect value={filters.sort??'entry'} onChange={v=>update({sort:v})} items={[{value:'entry',label:t('tradeExplorer.entry')},{value:'exit',label:t('tradeExplorer.exit')},{value:'pnl',label:'P&L'},{value:'pnlPercent',label:'P&L %'},{value:'holding',label:t('tradeExplorer.holding')}]} all="Sort"/></div></section>
 <section className="grid grid-cols-2 gap-3 lg:grid-cols-5">{statCards.map(([label,value])=><div className="surface-card p-4" key={String(label)}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</section>
 <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold">{t('tradeExplorer.trades')}</h2><span className="text-sm text-slate-500">{page.total}</span></div><div className="surface-card overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-4">{t('tradeExplorer.coin')}</th><th>{t('tradeExplorer.strategy')}</th><th>{t('tradeExplorer.entry')}</th><th>{t('tradeExplorer.exit')}</th><th>{t('tradeExplorer.return')}</th><th>{t('tradeExplorer.holding')}</th><th>{t('tradeExplorer.reason')}</th><th/></tr></thead><tbody>{page.items.map(row=><tr className="border-b dark:border-slate-800" key={row.id}><td className="p-4 font-bold">{row.coinSymbol}</td><td>{row.strategyName}<div className="text-xs text-slate-400">#{row.runId} · {row.runType}</div></td><td>{new Date(row.entryExecutionDate).toLocaleDateString(locale)}</td><td>{row.exitExecutionDate?new Date(row.exitExecutionDate).toLocaleDateString(locale):'OPEN'}</td><td className={row.pnlPercent>=0?'font-bold text-emerald-600':'font-bold text-rose-600'}>{row.exitExecutionDate?percent(row.pnlPercent):'—'}</td><td>{row.holdingDays} {t('tradeExplorer.days')}</td><td>{row.exitReason||'—'}</td><td><button className="rounded-lg border p-2" onClick={()=>void open(row)}><Search className="h-4 w-4"/></button></td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{page.items.map(row=><button key={row.id} onClick={()=>void open(row)} className="flex w-full items-center justify-between p-4 text-left"><div><p className="font-bold">{row.coinSymbol} · {row.strategyName}</p><p className="text-xs text-slate-500">{new Date(row.entryExecutionDate).toLocaleDateString(locale)} · {row.holdingDays} {t('tradeExplorer.days')}</p></div><span className={row.pnlPercent>=0?'font-bold text-emerald-600':'font-bold text-rose-600'}>{row.exitExecutionDate?percent(row.pnlPercent):'OPEN'}</span></button>)}</div>{!loading&&!page.items.length&&<p className="p-10 text-center text-slate-500">{t('tradeExplorer.noTrades')}</p>}</div><div className="mt-4 flex justify-end gap-2"><button disabled={(filters.page??1)<=1} className="rounded-lg border px-4 py-2 disabled:opacity-40" onClick={()=>update({page:(filters.page??1)-1})}>{t('tradeExplorer.previous')}</button><span className="px-3 py-2">{filters.page}/{pages}</span><button disabled={(filters.page??1)>=pages} className="rounded-lg border px-4 py-2 disabled:opacity-40" onClick={()=>update({page:(filters.page??1)+1})}>{t('tradeExplorer.next')}</button></div></section>
 <TradeDetailModal detail={detail} note={note} setNote={setNote} close={()=>setDetail(null)} saveNote={saveNote} locale={locale} t={t}/></div>
}

 function TradeDetailModal({detail,note,setNote,close,saveNote,locale,t}:{detail:TradeDetail|null;note:string;setNote:(v:string)=>void;close:()=>void;saveNote:()=>void;locale:string;t:any}){const values=detail?.entrySnapshot?.values??{};const exitValues=detail?.exitSnapshot?.values??{};const chart=useMemo(()=>detail?.analysis.chart??[],[detail]);return <Modal isOpen={!!detail} onClose={close} title={detail?`${detail.trade.coinSymbol} · ${detail.trade.strategyName}`:''} maxWidth="max-w-6xl">{detail&&<div className="space-y-6"><div className="grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-6">{[[t('tradeExplorer.entry'),money(detail.trade.entryPrice,locale)],[t('tradeExplorer.exit'),detail.trade.exitExecutionDate?money(detail.trade.exitPrice,locale):t('tradeExplorer.openPosition')],[t('tradeExplorer.return'),detail.trade.exitExecutionDate?percent(detail.trade.pnlPercent):percent(detail.analysis.unrealizedPnlPercent??0)],[t('tradeExplorer.holding'),`${detail.trade.holdingDays||detail.analysis.daysOpen} ${t('tradeExplorer.days')}`],[t('tradeExplorer.fees'),money(detail.trade.totalFees,locale)],[t('tradeExplorer.reason'),detail.trade.exitReason||'—']].map(([k,v])=><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800" key={String(k)}><p className="text-xs text-slate-500">{k}</p><p className="mt-1 font-bold">{v}</p></div>)}</div><div className="grid gap-3 rounded-xl border p-4 text-sm sm:grid-cols-2"><div><p className="font-semibold">{t('tradeExplorer.entry')}</p><p>{t('tradeExplorer.signal')}: {new Date(detail.trade.entrySignalDate).toLocaleDateString(locale)}</p><p>{t('tradeExplorer.execution')}: {new Date(detail.trade.entryExecutionDate).toLocaleDateString(locale)}</p></div><div><p className="font-semibold">{t('tradeExplorer.exit')}</p><p>{t('tradeExplorer.signal')}: {detail.trade.exitSignalDate?new Date(detail.trade.exitSignalDate).toLocaleDateString(locale):'—'}</p><p>{t('tradeExplorer.execution')}: {detail.trade.exitExecutionDate?new Date(detail.trade.exitExecutionDate).toLocaleDateString(locale):'—'}</p></div></div>
 <section><h3 className="mb-2 font-bold">{t('tradeExplorer.priceChart')}</h3><div className="h-72 rounded-xl border p-3"><ResponsiveContainer><AreaChart data={chart}><CartesianGrid strokeDasharray="4 6" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>new Date(v).toLocaleDateString(locale,{month:'short',day:'numeric'})} minTickGap={35}/><YAxis domain={['auto','auto']}/><Tooltip labelFormatter={v=>new Date(v).toLocaleDateString(locale)} formatter={v=>money(Number(v),locale)}/><Area dataKey="close" stroke="#6366f1" fill="#6366f133" strokeWidth={2}/><ReferenceLine x={detail.trade.entryExecutionDate} stroke="#10b981" label="▲ BUY"/>{detail.trade.exitExecutionDate&&<ReferenceLine x={detail.trade.exitExecutionDate} stroke="#f43f5e" label="▼ SELL"/>}</AreaChart></ResponsiveContainer></div><p className="mt-2 text-xs text-amber-600">{t('tradeExplorer.dailyClose')}</p></section>
 <div className="grid gap-4 lg:grid-cols-2"><RuleBox title={t('tradeExplorer.whyEntry')} snapshot={detail.entrySnapshot}/><RuleBox title={t('tradeExplorer.whyExit')} snapshot={detail.exitSnapshot}/></div><div className="grid gap-4 lg:grid-cols-2"><SnapshotBox title={t('tradeExplorer.entrySnapshot')} values={values}/><SnapshotBox title={t('tradeExplorer.exitSnapshot')} values={exitValues}/></div>
 <section><h3 className="font-bold">{t('tradeExplorer.journey')}</h3><div className="mt-3 grid gap-3 sm:grid-cols-3"><Metric label={t('tradeExplorer.bestClose')} value={percent(detail.analysis.excursion.bestPercent)} good/><Metric label={t('tradeExplorer.worstClose')} value={percent(detail.analysis.excursion.worstPercent)}/><Metric label={t('tradeExplorer.return')} value={detail.trade.exitExecutionDate?percent(detail.trade.pnlPercent):percent(detail.analysis.unrealizedPnlPercent??0)} good={(detail.trade.pnlPercent??0)>=0}/></div></section>
 <section><h3 className="font-bold">{t('tradeExplorer.postExit')}</h3><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-5">{(detail.analysis.postExit??[]).map(x=><Metric key={x.days} label={`+${x.days}D`} value={x.returnPercent==null?t('tradeExplorer.notEnough'):percent(x.returnPercent)} good={(x.returnPercent??-1)>=0}/>)}</div></section>
 <section><h3 className="mb-2 font-bold">{t('tradeExplorer.notes')}</h3><textarea className="min-h-24 w-full rounded-xl border bg-transparent p-3" value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/><button className="primary-action mt-2" onClick={saveNote}>{t('tradeExplorer.saveNote')}</button></section></div>}</Modal>}
function RuleBox({title,snapshot}:{title:string;snapshot:any}){return <section className="rounded-xl border p-4"><h3 className="font-bold">{title}</h3><div className="mt-3 space-y-2">{snapshot?.conditions?.length?snapshot.conditions.map((r:any,i:number)=><div className="flex justify-between text-sm" key={i}><span>{r.condition.left} {r.condition.operator==='gt'?'>':'<'} {r.condition.rightField||r.condition.value}</span><span className={r.matched?'text-emerald-600':'text-rose-600'}>{r.matched?'✓':'✗'} · {Number(r.leftValue).toFixed(2)} / {Number(r.rightValue).toFixed(2)}</span></div>):<p className="text-sm text-slate-500">—</p>}</div></section>}
function SnapshotBox({title,values}:{title:string;values:Record<string,number>}){return <section className="rounded-xl border p-4"><h3 className="font-bold">{title}</h3><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(values||{}).map(([k,v])=><div className="rounded-lg bg-slate-50 p-2 dark:bg-slate-800" key={k}><p className="text-xs text-slate-500">{k}</p><p className="font-semibold">{Number(v).toFixed(2)}</p></div>)}</div></section>}
function Metric({label,value,good=false}:{label:string;value:string;good?:boolean}){return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 font-bold ${good?'text-emerald-600':''}`}>{value}</p></div>}
