import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Target, Wallet, ShoppingBag, ArrowRight } from 'lucide-react'
import GoalForm from '@/components/purchase-goals/GoalForm'
import ProductImage from '@/components/purchase-goals/ProductImage'
import { purchaseGoalsApi, type NewGoal, type PurchaseGoal, type PurchaseStatus } from '@/services/purchaseGoalsService'
import { useToast } from '@/contexts/ToastContext'
import { useTranslation } from 'react-i18next'

const priorities:Record<string,number>={MUST_HAVE:0,HIGH:1,MEDIUM:2,LOW:3,SOMEDAY:4}
const money=(n:number,c:string)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:2}).format(n)
export default function PurchaseGoalsPage(){
 const toast=useToast();const {t}=useTranslation();const [goals,setGoals]=useState<PurchaseGoal[]>([]);const [loading,setLoading]=useState(true);const [open,setOpen]=useState(false);const [filter,setFilter]=useState<'ALL'|PurchaseStatus>('ALL')
 async function load(){try{setGoals(await purchaseGoalsApi.list())}catch(e){toast.error((e as Error).message)}finally{setLoading(false)}} useEffect(()=>{void load()},[])
 const visible=useMemo(()=>goals.filter(g=>filter==='ALL'||g.displayStatus===filter).sort((a,b)=>priorities[a.priority]-priorities[b.priority]||+new Date(a.createdAt)-+new Date(b.createdAt)),[goals,filter])
 const active=goals.filter(g=>!['PURCHASED','CANCELLED'].includes(g.status));const totals=active.reduce<Record<string,{target:number;saved:number}>>((a,g)=>{a[g.currency]??={target:0,saved:0};a[g.currency].target+=g.targetAmount;a[g.currency].saved+=g.savedAmount;return a},{})
 const next=active.slice().sort((a,b)=>priorities[a.priority]-priorities[b.priority]||b.progress-a.progress)[0]
 async function create(v:NewGoal){try{await purchaseGoalsApi.create(v);toast.success(t('purchaseGoals.created'));await load()}catch(e){toast.error((e as Error).message);throw e}}
 return <div className="min-h-full bg-slate-50 p-4 dark:bg-slate-950 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-indigo-500">{t('purchaseGoals.eyebrow')}</p><h1 className="text-3xl font-bold text-slate-950 dark:text-white">{t('purchaseGoals.title')}</h1><p className="mt-1 text-sm text-slate-500">{t('purchaseGoals.subtitle')}</p></div><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 font-semibold text-white shadow-lg shadow-indigo-500/20"><Plus size={18}/>{t('purchaseGoals.newGoal')}</button></header>
 <section className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><Target className="text-indigo-500"/><p className="mt-3 text-sm text-slate-500">{t('purchaseGoals.activeTarget')}</p>{Object.entries(totals).map(([c,v])=><p key={c} className="text-xl font-bold dark:text-white">{money(v.target,c)}</p>)}</div><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><Wallet className="text-emerald-500"/><p className="mt-3 text-sm text-slate-500">{t('purchaseGoals.totalSaved')}</p>{Object.entries(totals).map(([c,v])=><p key={c} className="text-xl font-bold dark:text-white">{money(v.saved,c)}</p>)}</div><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><ShoppingBag className="text-amber-500"/><p className="mt-3 text-sm text-slate-500">{t('purchaseGoals.completed')}</p><p className="text-xl font-bold dark:text-white">{goals.filter(g=>g.status==='PURCHASED').length} / {goals.filter(g=>g.status!=='CANCELLED').length}</p></div></section>
 {next&&<Link to={`/purchase-goals/${next.id}`} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-gradient-to-r from-indigo-600 to-violet-600 p-5 text-white shadow-xl"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-200">{t('purchaseGoals.nextTarget')} · {t(`purchaseGoals.priorities.${next.priority}`)}</p><h2 className="mt-1 text-xl font-bold">{next.name}</h2><p className="text-sm text-indigo-100">{money(next.savedAmount,next.currency)} {t('purchaseGoals.saved')} · {money(next.remainingAmount,next.currency)} {t('purchaseGoals.remaining')} {next.estimatedMonths&&`· ${t('purchaseGoals.months',{count:Number(next.estimatedMonths.toFixed(1))})}`}</p></div><div className="flex min-w-52 items-center gap-3"><div className="h-2 flex-1 rounded-full bg-white/20"><div className="h-full rounded-full bg-white" style={{width:`${Math.min(100,Math.max(0,next.progress))}%`}}/></div><b>{Math.round(next.progress)}%</b><ArrowRight/></div></Link>}
 <div className="flex gap-2 overflow-x-auto">{(['ALL','WANTED','SAVING','READY','PURCHASED','CANCELLED'] as const).map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-full px-4 py-2 text-sm font-semibold ${filter===x?'bg-slate-900 text-white dark:bg-white dark:text-slate-900':'bg-white text-slate-500 dark:bg-slate-900'}`}>{t(`purchaseGoals.filters.${x}`)}</button>)}</div>
 {loading?<p className="text-slate-500">{t('purchaseGoals.loading')}</p>:<section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{visible.map(g=>{const item=g.items[0];return <Link key={g.id} to={`/purchase-goals/${g.id}`} className="group overflow-hidden rounded-2xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl dark:border-slate-800 dark:bg-slate-900">{item?<ProductImage item={item}/>:<div className="h-24 bg-gradient-to-br from-indigo-500 to-violet-500"/>}<div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-bold text-slate-950 dark:text-white">{g.name}</h3><p className="text-xs text-slate-500">{t('purchaseGoals.items',{count:g.items.length})} · {t(`purchaseGoals.priorities.${g.priority}`)}</p></div><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-bold text-indigo-600 dark:bg-indigo-950">{t(`purchaseGoals.statuses.${g.displayStatus}`)}</span></div><p className="mt-4 text-2xl font-bold dark:text-white">{money(g.targetAmount,g.currency)}</p><div className="mt-4 flex justify-between text-xs text-slate-500"><span>{money(g.savedAmount,g.currency)} {t('purchaseGoals.saved')}</span><span>{Math.round(g.progress)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-emerald-400" style={{width:`${Math.min(100,Math.max(0,g.progress))}%`}}/></div></div></Link>})}</section>}</div><GoalForm open={open} onClose={()=>setOpen(false)} onSave={create}/></div>
}
