import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useNavigate, useParams } from 'react-router-dom'
import Chart from 'react-apexcharts'
import { ArrowLeft, ExternalLink, Plus, Trash2 } from 'lucide-react'
import ProductImage from '@/components/purchase-goals/ProductImage'
import PurchaseActionDialog, { type PurchaseAction } from '@/components/purchase-goals/PurchaseActionDialog'
import ConfirmDialog from '@/components/common/ConfirmDialog'
import { purchaseGoalsApi, type PurchaseGoal, type PurchaseItem, type SavingTransaction } from '@/services/purchaseGoalsService'
import { useToast } from '@/contexts/ToastContext'

const money=(n:number,c:string)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:2}).format(n)
const today=()=>new Date().toISOString().slice(0,10)
const input='h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-indigo-500 dark:border-slate-700 dark:bg-slate-950'

export default function PurchaseGoalDetailPage(){
 const {id}=useParams(); const nav=useNavigate(); const toast=useToast(); const {t,i18n}=useTranslation(); const goalId=Number(id)
 const [goal,setGoal]=useState<PurchaseGoal|null>(null)
 const [saving,setSaving]=useState({amount:'',date:today(),note:''})
 const [item,setItem]=useState({name:'',currentPrice:'',targetPrice:'',imageUrl:'',productUrl:'',category:''})
 const [dialog,setDialog]=useState<PurchaseAction|null>(null)
 const [confirming,setConfirming]=useState<{type:'goal'}|{type:'saving';id:number}|null>(null)
 async function load(){try{setGoal(await purchaseGoalsApi.get(goalId))}catch(e){toast.error((e as Error).message)}}
 useEffect(()=>{void load()},[goalId])
 async function action(work:()=>Promise<PurchaseGoal>,message:string){try{setGoal(await work());toast.success(message)}catch(e){toast.error((e as Error).message)}}
 async function addSaving(e:React.FormEvent){e.preventDefault();await action(()=>purchaseGoalsApi.addSaving(goalId,{amount:Number(saving.amount),date:new Date(saving.date).toISOString(),note:saving.note}),t('purchaseGoalDetail.savingAdded'));setSaving({amount:'',date:today(),note:''})}
 async function addItem(e:React.FormEvent){e.preventDefault();if(!goal)return;await action(()=>purchaseGoalsApi.addItem(goalId,{...item,currentPrice:Number(item.currentPrice),targetPrice:item.targetPrice?Number(item.targetPrice):null,currency:goal.currency,priority:goal.priority,status:'WANTED',imageFit:'COVER',imagePositionX:50,imagePositionY:50,imageZoom:1}),t('purchaseGoalDetail.itemAdded'));setItem({name:'',currentPrice:'',targetPrice:'',imageUrl:'',productUrl:'',category:''})}
 const savingsSeries=useMemo(()=>{if(!goal)return[];let total=0;return [...goal.savings].sort((a,b)=>+new Date(a.date)-+new Date(b.date)).map(s=>[+new Date(s.date),total+=s.amount])},[goal])
 if(!goal)return <div className="p-8 text-slate-500">{t('purchaseGoals.loading')}</div>
 const chartOptions:any={chart:{toolbar:{show:false},background:'transparent',animations:{enabled:window.innerWidth>=640}},stroke:{curve:'stepline',width:3},colors:['#6366f1'],xaxis:{type:'datetime',labels:{hideOverlappingLabels:true,trim:true}},yaxis:{labels:{minWidth:0,maxWidth:56,formatter:(v:number)=>new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(v)}},tooltip:{theme:'dark',shared:true,intersect:false},legend:{position:'bottom'},grid:{padding:{left:0,right:4}},annotations:{yaxis:[{y:goal.targetAmount,borderColor:'#10b981',label:{text:t('purchaseGoalDetail.goal')}}]},theme:{mode:document.documentElement.classList.contains('dark')?'dark':'light'},responsive:[{breakpoint:640,options:{chart:{toolbar:{show:false}},legend:{position:'bottom'},xaxis:{tickAmount:3}}}]}
 function editSaving(s:SavingTransaction){setDialog({type:'saving',savingId:s.id,amount:s.amount,date:s.date,note:s.note})}
 function updatePrice(i:PurchaseItem){setDialog({type:'price',itemId:i.id,amount:i.currentPrice,date:today()})}
 function purchase(i:PurchaseItem){setDialog({type:'purchase',itemId:i.id,amount:i.currentPrice,date:today()})}
 async function submitDialog(value:PurchaseAction){if(value.type==='saving')await action(()=>purchaseGoalsApi.updateSaving(goalId,value.savingId,{amount:value.amount,date:new Date(value.date).toISOString(),note:value.note}),t('purchaseGoalDetail.savingUpdated'));else if(value.type==='price')await action(()=>purchaseGoalsApi.updatePrice(value.itemId,value.amount,new Date(value.date).toISOString()),t('purchaseGoalDetail.priceUpdated'));else await action(()=>purchaseGoalsApi.purchase(value.itemId,value.amount,new Date(value.date).toISOString()),t('purchaseGoalDetail.purchased'))}
 async function confirmDelete(){if(!confirming)return;if(confirming.type==='goal'){await purchaseGoalsApi.remove(goalId);nav('/purchase-goals')}else await action(()=>purchaseGoalsApi.deleteSaving(goalId,confirming.id),t('purchaseGoalDetail.savingDeleted'))}
 const stats=[[t('purchaseGoalDetail.target'),money(goal.targetAmount,goal.currency)],[t('purchaseGoalDetail.saved'),money(goal.savedAmount,goal.currency)],[t('purchaseGoalDetail.remaining'),money(goal.remainingAmount,goal.currency)],[t('purchaseGoalDetail.progress'),`${goal.progress.toFixed(1)}%`]]
 return <div className="min-h-full bg-slate-50 p-4 dark:bg-slate-950 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
  <header className="flex flex-wrap items-start justify-between gap-4"><div><Link to="/purchase-goals" className="mb-3 flex items-center gap-2 text-sm font-semibold text-indigo-600"><ArrowLeft size={16}/>{t('purchaseGoalDetail.back')}</Link><h1 className="text-3xl font-bold dark:text-white">{goal.name}</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">{goal.notes||t('purchaseGoalDetail.noNotes')}</p></div><div className="flex gap-2"><button onClick={()=>void action(()=>purchaseGoalsApi.cancel(goal.id),t('purchaseGoalDetail.goalCancelled'))} className="rounded-xl border px-3 py-2 text-sm dark:border-slate-700">{t('purchaseGoalDetail.cancelGoal')}</button><button aria-label={t('purchaseGoalDetail.deleteGoal')} onClick={()=>setConfirming({type:'goal'})} className="rounded-xl border border-red-200 px-3 py-2 text-red-600"><Trash2 size={16}/></button></div></header>
  <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([key,value])=><div key={key} className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-sm text-slate-500">{key}</p><p className="mt-2 text-2xl font-bold dark:text-white">{value}</p></div>)}</section>
  <div className="h-3 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-emerald-400" style={{width:`${Math.min(100,Math.max(0,goal.progress))}%`}}/></div>
  <section><h2 className="mb-1 text-xl font-bold dark:text-white">{t(goal.items.length===1?'purchaseGoalDetail.product':'purchaseGoalDetail.items')}</h2><p className="mb-3 text-sm text-slate-500">{t('purchaseGoalDetail.purchasedValue',{value:money(goal.purchasedValue,goal.currency),active:money(goal.remainingItemValue,goal.currency)})}</p>
   <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{goal.items.map(i=><article key={i.id} className="overflow-hidden rounded-2xl border bg-white dark:border-slate-800 dark:bg-slate-900"><ProductImage item={i}/><div className="space-y-3 p-5"><div className="flex justify-between gap-2"><div><h3 className="font-bold dark:text-white">{i.name}</h3><p className="text-xs text-slate-500">{i.category||t('purchaseGoalDetail.uncategorized')} · {t(`purchaseGoals.statuses.${i.status}`)}</p></div><b className="dark:text-white">{money(i.currentPrice,i.currency)}</b></div>{i.targetPrice!==null&&<p className={i.currentPrice<=i.targetPrice?'text-sm text-emerald-600':'text-sm text-amber-600'}>{t(i.currentPrice<=i.targetPrice?'purchaseGoalDetail.belowTarget':'purchaseGoalDetail.aboveTarget',{value:money(Math.abs(i.currentPrice-i.targetPrice),i.currency)})}</p>}<p className="text-sm text-slate-500">{i.description}</p><div className="flex flex-wrap gap-2"><button onClick={()=>void updatePrice(i)} className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-semibold dark:bg-slate-800">{t('purchaseGoalDetail.updatePrice')}</button>{i.status!=='PURCHASED'&&<button onClick={()=>void purchase(i)} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white">{t('purchaseGoalDetail.markPurchased')}</button>}{i.status!=='CANCELLED'&&i.status!=='PURCHASED'&&<button onClick={()=>void action(()=>purchaseGoalsApi.cancelItem(i.id),t('purchaseGoalDetail.itemCancelled'))} className="rounded-lg border px-3 py-1.5 text-xs">{t('purchaseGoalDetail.cancel')}</button>}{i.productUrl&&<a href={i.productUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1 rounded-lg border px-3 py-1.5 text-xs"><ExternalLink size={12}/>{t('purchaseGoalDetail.viewProduct')}</a>}</div>{i.priceHistory.length>1&&<div className="h-36"><Chart type="line" height="100%" options={{...chartOptions,annotations:{}}} series={[{name:t('purchaseGoalDetail.price'),data:i.priceHistory.map(p=>[+new Date(p.date),p.price])}]}/></div>}</div></article>)}</div>
   <form onSubmit={addItem} className="mt-4 grid gap-2 rounded-2xl border border-dashed p-4 sm:grid-cols-3 dark:border-slate-700"><input required className={input} placeholder={t('purchaseGoalDetail.itemName')} value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/><input required min="0" step=".01" type="number" className={input} placeholder={t('purchaseGoalDetail.currentPrice')} value={item.currentPrice} onChange={e=>setItem({...item,currentPrice:e.target.value})}/><input min="0" step=".01" type="number" className={input} placeholder={t('purchaseGoalDetail.targetPrice')} value={item.targetPrice} onChange={e=>setItem({...item,targetPrice:e.target.value})}/><input type="url" className={input} placeholder={t('purchaseGoalDetail.imageUrl')} value={item.imageUrl} onChange={e=>setItem({...item,imageUrl:e.target.value})}/><input type="url" className={input} placeholder={t('purchaseGoalDetail.productUrl')} value={item.productUrl} onChange={e=>setItem({...item,productUrl:e.target.value})}/><button className="flex items-center justify-center gap-2 rounded-xl bg-indigo-600 p-2 font-semibold text-white"><Plus size={16}/>{t('purchaseGoalDetail.addItem')}</button></form>
  </section>
  <section className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold dark:text-white">{t('purchaseGoalDetail.savingsProgress')}</h2><p className="text-sm text-slate-500">{t('purchaseGoalDetail.savingsHelp')}</p><div className="mt-3 h-72"><Chart type="area" height="100%" options={chartOptions} series={[{name:t('purchaseGoalDetail.saved'),data:savingsSeries}]}/></div></div><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold dark:text-white">{t('purchaseGoalDetail.savingHistory')}</h2><form onSubmit={addSaving} className="my-4 grid gap-2"><input required step=".01" type="number" className={input} placeholder={t('purchaseGoalDetail.savingAmount')} value={saving.amount} onChange={e=>setSaving({...saving,amount:e.target.value})}/><input required type="date" className={input} value={saving.date} onChange={e=>setSaving({...saving,date:e.target.value})}/><input className={input} placeholder={t('purchaseGoalDetail.note')} value={saving.note} onChange={e=>setSaving({...saving,note:e.target.value})}/><button className="rounded-xl bg-indigo-600 p-2 font-semibold text-white">{t('purchaseGoalDetail.addSaving')}</button></form><div className="max-h-72 space-y-2 overflow-y-auto">{goal.savings.map(s=><div key={s.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><button onClick={()=>void editSaving(s)} className="text-left"><b className={s.amount>=0?'text-emerald-600':'text-red-500'}>{s.amount>=0?'+':''}{money(s.amount,goal.currency)}</b><p className="text-xs text-slate-500">{new Date(s.date).toLocaleDateString(i18n.language)} · {s.note}</p></button><button aria-label={t('purchaseGoalDetail.deleteSaving')} onClick={()=>void action(()=>purchaseGoalsApi.deleteSaving(goal.id,s.id),t('purchaseGoalDetail.savingDeleted'))} className="text-red-500"><Trash2 size={16}/></button></div>)}</div></div></section>
  <PurchaseActionDialog action={dialog} onClose={()=>setDialog(null)} onSubmit={submitDialog}/>
  <ConfirmDialog isOpen={!!confirming} onClose={()=>setConfirming(null)} onConfirm={()=>void confirmDelete()} title={t(confirming?.type==='goal'?'purchaseGoalDialogs.deleteGoalTitle':'purchaseGoalDialogs.deleteSavingTitle')} message={t(confirming?.type==='goal'?'purchaseGoalDialogs.deleteGoalMessage':'purchaseGoalDialogs.deleteSavingMessage')} confirmText={t('purchaseGoalDialogs.delete')} variant="danger"/>
 </div></div>
}
