import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Activity, AlertTriangle, Info, RefreshCw } from 'lucide-react'
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import Modal from '@/components/common/Modal'
import { getMarketBreadth, getMarketBreadthCoins, getMarketBreadthHistory, type BreadthMetric, type BreadthPeriod, type BreadthResponse, type HistoryPoint, type MetricCoin, type Ratio } from '@/services/marketBreadthService'

const formulaKeys: Record<BreadthMetric, string> = {above_ma7:'aboveMA7',above_ma25:'aboveMA25',above_ma99:'aboveMA99',ma7_above_ma25:'ma7AboveMA25',ma25_above_ma99:'ma25AboveMA99',bullish:'bullishFormula',bearish:'bearishFormula',rsi_above_50:'rsiAbove50',rsi_above_60:'rsiAbove60',rsi_above_70:'rsiAbove70',rsi_below_30:'rsiBelow30',positive_24h:'positive24h'}
function Selector<T extends string>({value,values,onChange,labels}:{value:T;values:T[];onChange:(v:T)=>void;labels?:Record<string,string>}){return <div className="inline-flex rounded-xl bg-slate-100 p-1 dark:bg-slate-800">{values.map(v=><button key={v} onClick={()=>onChange(v)} className={`rounded-lg px-4 py-2 text-xs font-bold uppercase transition ${v===value?'bg-white text-indigo-600 shadow dark:bg-slate-700 dark:text-indigo-300':'text-slate-500'}`}>{labels?.[v]??v}</button>)}</div>}
function MetricCard({title,value,metric,onOpen,formula,coinsLabel}:{title:string;value:Ratio;metric?:BreadthMetric;onOpen:(m:BreadthMetric,t:string)=>void;formula?:string;coinsLabel:string}){const body=<div className="surface-card p-4 transition hover:-translate-y-0.5 hover:border-indigo-400"><p className="text-sm font-medium text-slate-500 dark:text-slate-400">{title}</p><p className="mt-2 text-3xl font-bold text-slate-900 dark:text-white">{value.percentage.toFixed(1)}%</p><p className="mt-1 text-xs text-slate-400">{value.count} / {value.total} {coinsLabel}</p></div>;return metric?<button className="text-left" title={`${formula} · ${value.count}/${value.total}`} onClick={()=>onOpen(metric,title)}>{body}</button>:body}

export default function MarketBreadthPage(){
 const {t,i18n}=useTranslation();const [period,setPeriod]=useState<BreadthPeriod>('30d');const [data,setData]=useState<BreadthResponse|null>(null),[history,setHistory]=useState<HistoryPoint[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');const [modal,setModal]=useState<{title:string;coins:MetricCoin[];loading:boolean}|null>(null)
 const load=async(soft=false)=>{soft?setRefreshing(true):setLoading(true);try{setError('');setData(await getMarketBreadth())}catch(e){setError(e instanceof Error?e.message:t('marketBreadth.errors.load'))}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void load(false)},[]);useEffect(()=>{getMarketBreadthHistory(period).then(r=>setHistory(r.points)).catch(()=>setHistory([]))},[period])
 const drill=async(metric:BreadthMetric,title:string)=>{setModal({title,coins:[],loading:true});try{const coins=await getMarketBreadthCoins(metric);setModal({title,coins,loading:false})}catch{setModal({title,coins:[],loading:false})}}
 const formula=(metric:BreadthMetric)=>t(`marketBreadth.formulas.${formulaKeys[metric]}`)
 if(loading)return <div className="page-shell"><div className="h-40 animate-pulse rounded-3xl bg-slate-200 dark:bg-slate-800"/><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-28 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800"/>)}</div></div>
 if(error||!data)return <div className="surface-card mx-auto max-w-xl p-8 text-center"><AlertTriangle className="mx-auto mb-3 text-amber-500"/><p>{error||t('marketBreadth.errors.empty')}</p><button className="primary-action mt-4" onClick={()=>void load()}>{t('marketBreadth.actions.retry')}</button></div>
 const s=data.snapshot;const btcSummary=data.btc.change24h>0&&data.btc.breadthChange7d<0?'divergingDown':data.btc.change24h<0&&data.btc.breadthChange7d>0?'divergingUp':'sameDirection';const locale=i18n.language.startsWith('tr')?'tr-TR':'en-US';const coinsLabel=t('marketBreadth.coins')
 return <div className="page-shell">
  <section className="page-hero"><div className="relative z-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-indigo-300">{t('marketBreadth.eyebrow')}</p><h1 className="mt-2 text-3xl font-bold">{t('marketBreadth.title')}</h1><p className="mt-2 text-sm text-slate-300">{t('marketBreadth.universe')}</p></div><div className="flex items-center gap-3"><span className="rounded-xl border border-white/20 px-4 py-2 text-xs font-bold">1D</span><button aria-label={t('marketBreadth.actions.refresh')} title={t('marketBreadth.actions.refresh')} onClick={()=>void load(true)} className="rounded-xl border border-white/20 p-2.5"><RefreshCw className={`h-4 w-4 ${refreshing?'animate-spin':''}`}/></button></div></div></section>
  {data.coverage.ma99Valid*100<data.coverage.universeCoins*80&&<div className="flex gap-2 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-800 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-200"><AlertTriangle className="h-5 w-5 shrink-0"/>{t('marketBreadth.warnings.coverage',{valid:data.coverage.ma99Valid,total:data.coverage.universeCoins})}</div>}
  {data.coverage.excludedCoins>0&&<div className="flex gap-2 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-800 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-200"><AlertTriangle className="h-5 w-5 shrink-0"/>{t('marketBreadth.warnings.excluded',{count:data.coverage.excludedCoins})}</div>}
  <section className="grid gap-4 lg:grid-cols-[1.4fr_1fr]"><div className="surface-card p-6"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-500">{t('marketBreadth.score.title')}</p><p className="mt-1 text-5xl font-black">{s.scores.breadthScore.toFixed(1)}<span className="text-lg text-slate-400"> / 100</span></p><p className={`mt-2 font-semibold ${data.breadthMomentum.sevenDay>=0?'text-emerald-500':'text-rose-500'}`}>{data.breadthMomentum.sevenDay>=0?'+':''}{data.breadthMomentum.sevenDay.toFixed(1)} {t('marketBreadth.pp7d')}</p></div><div title={t('marketBreadth.score.formula')}><Info className="text-slate-400"/></div></div><div className="mt-6 grid grid-cols-3 gap-3">{(['trend','momentum','participation'] as const).map(k=><div key={k} className="rounded-xl bg-slate-50 p-3 text-center dark:bg-slate-800"><p className="text-xs text-slate-500">{t(`marketBreadth.score.${k}`)}</p><p className="mt-1 text-xl font-bold">{s.scores.components[k].toFixed(1)}</p></div>)}</div><p className="mt-4 text-xs text-slate-400">{t('marketBreadth.score.disclaimer')}</p></div>
  <div className="surface-card p-6"><h2 className="font-bold">{t('marketBreadth.btc.title')}</h2><div className="mt-5 grid grid-cols-2 gap-3"><div><p className="text-xs text-slate-500">{t('marketBreadth.btc.price')}</p><p className="text-2xl font-bold">${data.btc.price.toLocaleString(locale)}</p><p className={data.btc.change24h>=0?'text-emerald-500':'text-rose-500'}>{data.btc.change24h.toFixed(2)}%</p></div><div><p className="text-xs text-slate-500">{t('marketBreadth.btc.breadth7d')}</p><p className="text-2xl font-bold">{data.btc.breadthChange7d>=0?'+':''}{data.btc.breadthChange7d.toFixed(1)} pp</p></div></div><p className="mt-5 text-sm text-slate-500">{t(`marketBreadth.btc.${btcSummary}`)}</p></div></section>
  <section><h2 className="mb-3 text-lg font-bold">{t('marketBreadth.sections.participation')}</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[['advancing',s.participation.advancing],['declining',s.participation.declining],['unchanged',s.participation.unchanged],['adRatio',s.participation.advanceDeclineRatio?.toFixed(2)??'∞'],['netAdvance',`${s.participation.netAdvance>=0?'+':''}${s.participation.netAdvance}`]].map(([k,v])=><div className="surface-card p-4" key={k}><p className="text-xs text-slate-500">{t(`marketBreadth.metrics.${k}`)}</p><p className="mt-1 text-2xl font-bold">{v}</p></div>)}</div><div className="mt-3 grid grid-cols-2 gap-3"><MetricCard title={t('marketBreadth.metrics.positive24h')} value={s.positive24h} metric="positive_24h" formula={formula('positive_24h')} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title={t('marketBreadth.metrics.positive7d')} value={s.positive7d} onOpen={drill} coinsLabel={coinsLabel}/></div></section>
  <section><h2 className="mb-3 text-lg font-bold">{t('marketBreadth.sections.trend')}</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6"><MetricCard title={t('marketBreadth.metrics.aboveMA7')} value={s.trend.aboveMA7} metric="above_ma7" formula={formula('above_ma7')} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title={t('marketBreadth.metrics.aboveMA25')} value={s.trend.aboveMA25} metric="above_ma25" formula={formula('above_ma25')} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title={t('marketBreadth.metrics.aboveMA99')} value={s.trend.aboveMA99} metric="above_ma99" formula={formula('above_ma99')} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title="MA7 > MA25" value={s.trend.ma7AboveMA25} metric="ma7_above_ma25" formula={formula('ma7_above_ma25')} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title="MA25 > MA99" value={s.trend.ma25AboveMA99} metric="ma25_above_ma99" formula={formula('ma25_above_ma99')} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title="MA7 > MA25 > MA99" value={s.trend.bullish} metric="bullish" formula={formula('bullish')} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title={t('marketBreadth.metrics.bullish')} value={s.trend.bullish} metric="bullish" formula={formula('bullish')} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title={t('marketBreadth.metrics.mixed')} value={s.trend.mixed} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title={t('marketBreadth.metrics.bearish')} value={s.trend.bearish} metric="bearish" formula={formula('bearish')} onOpen={drill} coinsLabel={coinsLabel}/></div></section>
  <section><h2 className="mb-3 text-lg font-bold">{t('marketBreadth.sections.momentum')}</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><MetricCard title="RSI > 50" value={s.momentum.rsiAbove50} metric="rsi_above_50" formula={formula('rsi_above_50')} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title="RSI > 60" value={s.momentum.rsiAbove60} metric="rsi_above_60" formula={formula('rsi_above_60')} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title="RSI > 70" value={s.momentum.rsiAbove70} metric="rsi_above_70" formula={formula('rsi_above_70')} onOpen={drill} coinsLabel={coinsLabel}/><MetricCard title="RSI < 30" value={s.momentum.rsiBelow30} metric="rsi_below_30" formula={formula('rsi_below_30')} onOpen={drill} coinsLabel={coinsLabel}/></div></section>
  <section className="surface-card p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">{t('marketBreadth.history.title')}</h2><p className="text-xs text-slate-500">{t('marketBreadth.history.description')}</p></div><Selector value={period} values={['30d','90d','1y']} onChange={setPeriod} labels={{'30d':t('marketBreadth.periods.30d'),'90d':t('marketBreadth.periods.90d'),'1y':t('marketBreadth.periods.1y')}}/></div><div className="h-80">{history.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={history}><CartesianGrid strokeDasharray="3 3" opacity={.25}/><XAxis dataKey="date" tickFormatter={v=>new Date(v).toLocaleDateString(locale,{month:'short',day:'numeric'})}/><YAxis domain={[0,100]} unit="%"/><Tooltip labelFormatter={v=>new Date(String(v)).toLocaleString(locale)}/><Legend/><Line name={t('marketBreadth.score.title')} dataKey="breadthScore" stroke="#6366f1" dot={false}/><Line name={t('marketBreadth.metrics.aboveMA25')} dataKey="aboveMA25" stroke="#10b981" dot={false}/><Line name={t('marketBreadth.metrics.aboveMA99')} dataKey="aboveMA99" stroke="#f59e0b" dot={false}/><Line name="RSI > 50" dataKey="rsiAbove50" stroke="#06b6d4" dot={false}/></LineChart></ResponsiveContainer>:<div className="flex h-full items-center justify-center text-slate-500"><Activity className="mr-2"/>{t('marketBreadth.history.empty')}</div>}</div></section>
  <Modal isOpen={!!modal} onClose={()=>setModal(null)} title={modal?.title??t('marketBreadth.coins')} maxWidth="max-w-3xl">{modal?.loading?<div className="py-10 text-center">{t('marketBreadth.drilldown.loading')}</div>:modal?.coins.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">{t('marketBreadth.drilldown.coin')}</th><th>{t('marketBreadth.drilldown.price')}</th><th>24h</th><th>{t('marketBreadth.drilldown.metricValue')}</th></tr></thead><tbody>{modal.coins.map(c=><tr key={c.id} className="border-b border-slate-100 dark:border-slate-800"><td className="p-3 font-semibold">{c.symbol}<span className="ml-2 font-normal text-slate-400">{c.name}</span></td><td>${c.currentPrice.toLocaleString(locale)}</td><td>{c.change24h?.toFixed(2)??'—'}%</td><td>{c.metricValue.toFixed(2)}</td></tr>)}</tbody></table></div>:<p className="py-10 text-center text-slate-500">{t('marketBreadth.drilldown.empty')}</p>}</Modal>
 </div>
}
